# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
