# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20160310_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='full_name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='attending',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Guest'),
            preserve_default=False,
        ),
    ]
