# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_guest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='guest',
        ),
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Rsvp',
        ),
    ]
