# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20160318_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
