# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_auto_20160503_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dietary_other',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dietary_requirements',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
