# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_auto_20160518_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsvp.Group'),
        ),
    ]
