version: '2'
services:
  frontend:
    image: frankh/wedding-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/app/dist/static

  backend:
    image: frankh/wedding-backend
    volumes:
        - /dbs:/data
        - static:/app/dist/static
    environment:
        - DJANGO_ENVIRONMENT=production
        - "SECRET_KEY=$SECRET_KEY"

volumes:
  static:
    driver: local
